const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{wall: 0},
	{direction: 0},
	{moveDuration: 0},
	{dirChange: 0},
	{Bullet: 0},
	{Player: 0},
	{name: 0},
	{vert: 0},
	{hor: 0},
	{escape: 0},
	{eaten: 0},
	{escapeBlink: 0},
	{DestroyOutsideLayout: 0},
	{Timer: 0},
	{Ghost: 0},
	{TileSize: 0},
	{Score: 0},
	{Lives: 0},
	{playerRespawnTime: 0},
	{nbGhost: 0},
	{bigDotScore: 0},
	{dotScore: 0},
	{ghostEscapeTime: 0},
	{ghostBlinkTime: 0},
	{Alive: 0},
	{Game: 0},
	{Keyboard: 0},
	{aDir: 0},
	{Browser: 0},
	{ghostSpawn: 0},
	{BigDot: 0},
	{Dot: 0},
	{Text: 0},
	{playerSpawn: 0},
	{Fade: 0},
	{txtScore: 0},
	{txtGUI: 0},
	{ID: 0},
	{playerLives: 0}
];

self.InstanceType = {
	wall: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Ghost: class extends self.ISpriteInstance {},
	Game: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	aDir: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	ghostSpawn: class extends self.ISpriteInstance {},
	BigDot: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	playerSpawn: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	txtGUI: class extends self.ITextInstance {},
	playerLives: class extends self.ISpriteInstance {}
}